### ISSUE TITLE
Question: GPL-3.0 license required for this repo because of lightdock?

### ISSUE THREAD

**Issue by taoliu032** [siminegroup/E2EDNA2#15]
Hello @brianjimenez - Hope this message finds you well.

I am trying to figure out what license is the best choice for our E2EDNA 2.0 software and am aware that LightDock is licensed under GNU GPLv3. According to the license guide website ([link](https://choosealicense.com/licenses/)) provided by GitHub, the GNU GPLv3 seems to require "larger works using a licensed work" to be under the same license. Currently our E2EDNA 2.0 is under Apache-2 license which does not include the condition of "same license". In my opinion, Apache-2 license could give some flexibility because a future version of the E2EDNA software may provide multiple options of different auto-docker package.

A little summary of how LightDock is used in E2EDNA 2.0 now: lightdock-0.9.2 is installed by pip and the python scripts such as `lightdock3.py` are directly called without modification. Does our way of using LightDock fall into the category where we can only choose GNU GPLv3 for our E2EDNA 2.0? I am not sure of this question therefore would like to hear the LightDock developer's opinions. 

Thank you very much!

**Comment by brianjimenez** [comment]
Hi @taoliu032!

I don't see any problem licensing E2EDNA 2.0 with Apache-2 and using LightDock (GPLv3) since there is no modification or redistribution of the LightDock code and E2EDNA 2.0 has its own soul and entity as project (it makes use of LightDock for some specific parts of the protocol). No complains on my side, indeed, I think it's a wonderful choice licensing it through Apache-2, and makes the protocol more accessible to researchers and other developers to integrate it in their own pipelines and projects.

Really good job on E2EDNA 2.0!

**Comment by taoliu032** [comment]
Hi @brianjimenez! Thank you very much for the quick reply.

Thanks for clarifying my question. Apache-2 indeed provides great flexibility and GPLv3 facilitates sharing of open source code. I am novice in terms of dealing with licensing open-source software, so may I ask about the rationale behind using GPLv3 for LightDock? What were your considerations, if you don't mind sharing?

LightDock is a great tool! I look up to you when developing E2EDNA 2.0.

**Comment by brianjimenez** [comment]
LightDock was initially released on a custom open source free-for-academics license. Please note the open source part, since it was conditio sine qua non for me, but some constraints on the license were forced from the research center I was part of at that time. A few years after, I negotiated the transition to a more well-known open source license, thus GPLv3.

**Comment by taoliu032** [comment]
Thank you for sharing the history behind LightDock. Recently I have learned more about choosing an open-source license. After considerations, I am leaning away from Apache-2 as I would like to see other developers' modifications to E2EDNA to be open-source as well. LGPLv3 seems a better choice.

Thank you for your generous input!
